apiVersion: v1
kind: Service
metadata:
  name: myapp-production
  namespace: production
spec:
  selector:
    app: myapp-production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort