---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: myapp-secret
  namespace: staging
spec:
  encryptedData:
    API_KEY: AgCaSvu+bvHUsI9BlSFU2EwkLyL7ChL5Hyzz7jm9YiSk3IoLXp7ZbNdBpaYj0Zl95U1oUoUTAU8yO4RzYE5GFg6PSm3TxjcHAOxqorL++/z1NasChGKfNLCvlapEuFFgpGpzWmf7ZfBXBiWNKCZ3/FTV7goP0Oxz43AbHGgzH/x8Rs7qMopEuNOF5SRIWRhH0NFonRkD7U4MrT2pg8qNGYNA8oqwBbuaF13i92LzFYQGSwhkMyDpqVZhxrxk9JAxla7tuuMUFdcLVHCmhO0S7hHEFyVsY2/lgcnxPC7JCCvi+4MTsmAli7rFJys9WKo+j98xxO9RkPNiKKEsgM4IpBHcoRCqpL1HSBwOTAeJu9VdpzPWuh6uZB1dEJ19S6WcTYRIzaQlOoE1fXmlvlzl/6P/0b+V8vwWO7npNAyIAm9UmtITJUnf9PQNNhVontRVoE9spbXZfGNp3S7+5Z4BFK/UCrN0LwLURMDBgw6ZgjMZCCA2wGfdcEzRT71s7H0tAwkshPb/iRahaEDrpc9WDJ6TBhtQNISdnAvGDz7ts1HnO2lB9yZWr5OQaeXwOmNqcv09TGZKI9SmlQr+tJZp/fs4PuHrJtc+xGlytkRxIuCg6A+5fRWdFpzBpBiehZAlqreH4Aik8c6Z1C28CbPgO87JO0hjdTcsc6k5qAQ7PvdA1K/U3Qhy7Gv6yI7cxgiIRVvIfQZmLZOGmcYeTA==
    DB_PASSWORD: AgDKYQKIfRTxkuDMxYMSybfpYw1+4XL7iEhgD/aFhqc/o+LqhLpHbZupbBHeHQ3htzPdvwYudcKr0mEcRvdE5pCS2i0IkegHXBanBWedGmX+7m5PCFXuH0cYLm6w71EeG5USPdsv47Z8kTw7+ozC05LLJuOQYk3GGXjXSj8gtSRSqUld0GjlDhMXW5T/3nj6Xr62kUcJLPgQv0M9Qst7dTspT6WNeg5PG01sruoRmttngPQTmGiSasL4IQz6dEJB4TnNnLLad8crIzg3q6GrZU3TQDUk7v6fGaYgTPm/S8N5Qj+9XYhK3azyEZxh60cPVK4y8cUUx+JNWW3SD705hiJBxdCKx3w0/F4iZxexhETCBnbMQ7BtG7gmEKl4jHaeHKKLWnklNzC+slC/DQYEcvd0S8utgL+CYQYdw6Bz9jv8exLjdKFpjoIW7kjYBMbDUPeej4h1Mg5EhikbC/lLncI3+oazDbHl7QxYaceHCAFEMEYtHVx5psSsoGAPFjjYb2pB9TgVyoylnOCW3TRcoaS+1XWSSGQfqxxTZJBW2wewxaSYVsg97Bcs+RswHEyUl6NN068tmhtmRsxhI/t5/DelD2j4RmNvNLpuSlOp6fLMXs4cdAQ4ep7v/S+c3CfOkid9+nmaG3eMEEAmCzosmmPqmIrfrwZ5DczUKYU4H2IVgoE5qyHljqvoQwGzWtf+MqxU9XwrQ+ME4XT6TeLGTA==
  template:
    metadata:
      creationTimestamp: null
      name: myapp-secret
      namespace: staging
    type: Opaque
